version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      nav-designsystem:
        patterns:
          - '@navikt/aksel-*'
          - '@navikt/ds-*'
        update-types:
          - 'major'
      react:
        patterns:
          - 'react'
          - 'react-dom'
        update-types:
          - 'major'
      minor-and-patch:
        patterns:
          - '*'
        update-types:
          - 'patch'
          - 'minor'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
