apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksansvarlig-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.02.26_09.22-a08b941e2c0d
  port: 8080
  ingresses:
    - https://arbeidsmarkedstiltak.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      claims:
        groups:
          - id: 2cf8d881-c2da-47b5-b409-fa088440a629 # 0000-GA-TILTAK-ANSVARLIG, NAV Prod
  gcp:
    buckets:
      - name: amt-tiltaksansvarlig-flate-prod
        cascadingDelete: false
  observability:
      autoInstrumentation:
        enabled: true
        runtime: nodejs
      logging:
        destinations:
          - id: elastic
          - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: amt-tiltak
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-tiltaksansvarlig-flate-prod"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/amt-tiltak", "toUrl": "http://amt-tiltak",
              "toApp": { "name": "amt-tiltak", "namespace": "amt", "cluster": "prod-gcp" }
            }
          ]
        }
