apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksansvarlig-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.02.25_08.04-6f896bb4dffe
  port: 8080
  ingresses:
    - https://amt-tiltaksansvarlig-flate.dev.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      claims:
        groups:
          - id: ace70121-3382-47b0-a91d-f20a6b481a70
  gcp:
    buckets:
      - name: amt-tiltaksansvarlig-flate-dev
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-tiltaksansvarlig-flate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          }
        }
