apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: amt-tiltaksansvarlig-flate
  namespace: amt
  labels:
    team: amt
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.08.25_08.52-2e34d1784892
  port: 8080
  ingresses:
    - https://arbeidsmarkedstiltak.intern.dev.nav.no
    - https://arbeidsmarkedstiltak.ansatt.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    disableAutoScaling: true
    min: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      claims:
        groups:
          - id: 52bb9196-b071-4cc7-9472-be4942d33c4b # 0000-GA-TILTAK-ANSVARLIG, NAV Preprod
  gcp:
    buckets:
      - name: amt-tiltaksansvarlig-flate-dev
        cascadingDelete: false
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    outbound:
      rules:
        - application: amt-tiltak
  env:
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": {
            "bucketName": "amt-tiltaksansvarlig-flate-dev"
          },
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "proxies": [
            {
              "fromPath": "/amt-tiltak", "toUrl": "http://amt-tiltak",
              "toApp": { "name": "amt-tiltak", "namespace": "amt", "cluster": "dev-gcp" }
            }
          ]
        }
