name: Cypress cache
on:
  push:
    branches:
      - main

jobs:
  cypress-cache:
    name: Cypress cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Cypress binary cache
        uses: actions/cache@v4
        id: cypress-cache
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install cypress binary
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile && pnpm exec cypress install
