name: Lint & tests
on:
  pull_request:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  lint-and-test:
    name: Lint & run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
