name: Rydd applikasjon for PR
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  cleanup-pr:
    name: Rydd applikasjon for PR
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # Used to authenticate with Google Cloud
    steps:
      - name: Authenticate to Google Cloud
        if: steps.check_artifact.outputs.exists == 'true'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/696882554390/locations/global/workloadIdentityPools/github/providers/github-action
          service_account: amt-tiltaksansvarlig-flate-gcs@amt-dev-d98f.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        if: steps.check_artifact.outputs.exists == 'true'
        uses: google-github-actions/setup-gcloud@v1
      - name: Delete files on GCS
        if: steps.check_artifact.outputs.exists == 'true'
        run: |
          if gsutil ls gs://amt-tiltaksansvarlig-flate-dev/pr-${{ github.event.number }} > /dev/null 2>&1; then
              gsutil rm -r gs://amt-tiltaksansvarlig-flate-dev/pr-${{ github.event.number }}
          else
              echo "Directory gs://amt-tiltaksansvarlig-flate-dev/pr-${{ github.event.number }} does not exist."
          fi

