name: Run tests
on:
  push:
    branches-ignore:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Run tests
        run: npm run test
